#!/bin/bash

CAFE_VOLUME=1
RAIN_VOLUME=1

if [ $# -ne 0 ]
then
    if [ $# -ne 2 ]
    then
        >&2 echo "Usage: $0 <cafe volume (0-15)> <rain volume (0-15)>"
        exit 1
    fi
    CAFE_VOLUME=$1
    RAIN_VOLUME=$2
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

play --combine mix -v $CAFE_VOLUME $DIR/audio/cafe.mp3 -v $RAIN_VOLUME $DIR/audio/rain.mp3 repeat -
